# Generated by Django 5.1.2 on 2024-10-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_abouthomepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutHomePage',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
