# Generated by Django 5.1.2 on 2024-10-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
