# Generated by Django 5.1.2 on 2024-10-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producthomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthomepage',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
