# Generated by Django 5.1.2 on 2024-10-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projecthomepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthomepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projecthomepage',
            name='price',
        ),
    ]
