# Generated by Django 5.1.2 on 2024-10-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
