# Generated by Django 5.1.2 on 2024-10-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='about/')),
                ('title_1', models.CharField(max_length=120)),
                ('description_1', models.TextField()),
                ('image_2', models.ImageField(upload_to='about/')),
                ('title_2', models.CharField(max_length=120)),
                ('description_2', models.TextField()),
            ],
        ),
    ]
