# Generated by Django 5.1.2 on 2024-10-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mage', models.ImageField(upload_to='cert/')),
            ],
        ),
    ]
