# Generated by Django 5.1.2 on 2024-10-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
