# Generated by Django 5.1.2 on 2024-10-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_contact_name_alter_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
