# Generated by Django 5.1.2 on 2024-10-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthomepage',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='abouthomepage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='abouthomepage',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='abouthomepage',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='abouthomepage',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='abouthomepage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_1_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_1_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_1_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_2_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_1_az',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_1_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_1_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_2_az',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_2_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_2_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='producthomepage',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producthomepage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producthomepage',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producthomepage',
            name='title_az',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='producthomepage',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='producthomepage',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projecthomepage',
            name='title_az',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projecthomepage',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projecthomepage',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='description_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='description_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
