# Generated by Django 5.1.2 on 2024-10-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_abouthomepage_description_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouthomepage',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='abouthomepage',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='description_1_az',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='description_2_az',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_1_az',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_2_az',
        ),
        migrations.RemoveField(
            model_name='producthomepage',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='producthomepage',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='projecthomepage',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='description_az',
        ),
    ]
