# Generated by Django 5.1.2 on 2024-10-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bunlarbax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
